[package]
name = "video-compressor-tauri"
version = "0.1.0"
description = "本地视频/图片压缩工具 (Tauri + ffmpeg sidecar)"
authors = ["lvruifeng"]
edition = "2021"

[lib]
name = "video_compressor_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = 2
lto = true
